Updated readme to better direct users to our primary page for Guardian
protectai/modelscan pull request #210
Opened 2024-10-11 18:27 UTC by chrisking

This provides an overview of how Guardian works as an image and some better supporting text, along with links to our official pages.

2024-10-12 00:58 UTC, badarahmed requested changes

2024-10-12 00:58 UTC, badarahmed commented on README.md
> +## Scanning Models At Scale
Claude suggested re-write below. Won't recommend using it verbatim but I like it!

# Elevate Your AI Security with Guardian

While ModelScan offers robust open-source scanning, organizations seeking comprehensive AI security should consider [Guardian](https://protectai.com/guardian), our enterprise-grade solution.

![Guardian Overview](/imgs/guardian_overview.png)

## Guardian: Advanced Protection for Enterprise AI

Guardian takes your AI security to the next level:

1. **Cutting-Edge Scanning**: Access our latest scanners, broader model support, and automatic model format detection.

2. **Proactive Security**: Define and enforce security requirements for Hugging Face models before they enter your environment—no code changes required.

3. **Enterprise-Wide Coverage**: Implement a cohesive security posture across your organization, seamlessly integrating with your CI/CD pipelines.

4. **Comprehensive Audit Trail**: Gain full visibility into all scans and results, empowering you to identify and mitigate threats effectively.

Ready to fortify your AI infrastructure? [Explore Guardian today](https://protectai.com/guardian) and safeguard your organization's AI assets.

2024-10-14 17:01 UTC, seanpmorgan approved these changes

2024-10-14 19:26 UTC, badarahmed commented on README.md
> +ModelScan offers robust open-source scanning. If you need comprehensive AI security, consider [Guardian](https://protectai.com/guardian). It is our enterprise-grade solution.
enterprise-grade product (vs solution)

2024-10-14 19:27 UTC, badarahmed commented on README.md
> +Copyright 2023 Protect AI
Update to 2024

2024-10-14 23:13 UTC, badarahmed approved these changes
🚢

2024-10-15 11:40 UTC, merged